name: Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        schema: [staging, production]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - name: Load environment variables
        run: echo "SCHEMA=${{ matrix.schema }}" >> $GITHUB_ENV
      - run: |
          if [ "${{ matrix.schema }}" == "staging" ]; then
            cp .env.staging .env
          else
            cp .env.production .env
          fi
      - run: npm run build -- --schema ${{ matrix.schema }}
      - name: Publish to Expo
        run: expo publish --release-channel ${{ matrix.schema }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
