name: preview

on:
  pull_request:
    branches:
      - develop
      - main
      - "release/*"

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Create preview for QA
        if: github.event.pull_request.base.ref == 'develop' || startsWith(github.event.pull_request.base.ref, 'release/')
        uses: expo/expo-github-action/preview@v8
        with:
          command: APP_VARIANT=qa eas update --auto

      - name: Create preview for Production
        if: github.event.pull_request.base.ref == 'main'
        uses: expo/expo-github-action/preview@v8
        with:
          command: APP_VARIANT=prod eas update --auto
